name: Run Tests

on:
  push:

jobs:
  linux-x86:
    name: linux-x86
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build and Check
        run: nix-build
