name: Run Tests

on:
  push:

jobs:
  linux-x86:
    name: linux-x86
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build and Check
        run: nix-build
  windows-x86:
    name: windows-x86
    runs-on: windows-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Install Zig 0.11.0
        run: |
          curl -L https://ziglang.org/download/0.11.0/zig-windows-x86_64-0.11.0.zip -o ./zig.zip
          7z x zig.zip
          # zig 0.11.0 should be installed under ./zig-windows-x86_64-0.11.0/zig.exe
          echo INFO: ls
          ls
          echo INFO: GITHUB_PATH
          echo $GITHUB_PATH
          echo INFO: pwd
          pwd
          echo INFO: cat $GITHUB_PATH
          cat $GITHUB_PATH
          echo INFO: $(pwd)/zig-windows-x86_64-0.11.0 >> \$GITHUB_PATH
          echo "$(pwd)/zig-windows-x86_64-0.11.0" >> $GITHUB_PATH
          echo INFO: cat $GITHUB_PATH
          cat $GITHUB_PATH
          echo INFO: zig version
          zig version
      - name: Install GCC 13.2.0
        run: |
          curl -L https://github.com/niXman/mingw-builds-binaries/releases/download/13.2.0-rt_v11-rev1/x86_64-13.2.0-release-posix-seh-ucrt-rt_v11-rev1.7z -o ./mingw.7z
          7z x mingw.7z
          # cc and gcc 13.2.0 should be installed under ./mingw64/bin/<cc|gcc>.exe
          echo "$(pwd)/mingw64/bin" >> $GITHUB_PATH
          cc --version
      - name: Install QBE/winabi
        run: |
          git clone git://c9x.me/qbe.git --branch winabi --depth 1
          cd qbe
          make
          cd ..
          # qbe should be installed under ./qbe/qbe.exe
          echo "$(pwd)/qbe" >> $GITHUB_PATH
          qbe --version
      - name: Build and Check
        run: |
          zig build test
